name: Deploy Workflow

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    outputs:
      build-tag: ${{ steps.build-tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Assume role in Cloud Platform
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}

      - name: Login to container repository
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Store current date
        run: echo "BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S%z)" >> $GITHUB_ENV

      - name: Store build tag
        id: build-tag
        run: |
          prefix="cait"
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          short_version=$(git rev-parse --short ${{ github.sha }})
          build_tag=$prefix-$branch-$short_version
          echo "BUILD_TAG=$build_tag" >> $GITHUB_ENV
          echo "tag=$build_tag" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          docker build \
            --build-arg APP_BUILD_DATE=${{ env.BUILD_DATE }} \
            --build-arg APP_BUILD_TAG=${{ env.BUILD_TAG }} \
            --build-arg APP_GIT_COMMIT=${{ github.sha }} \
            -t ${{ vars.ECR_URL }}:${{ github.sha }} .

      - name: Push to ECR
        run: |
          docker tag ${{ vars.ECR_URL }}:${{ github.sha }} ${{ vars.ECR_URL }}:staging.latest
          docker tag ${{ vars.ECR_URL }}:${{ github.sha }} ${{ vars.ECR_URL }}:production.latest
          docker push ${{ vars.ECR_URL }}:${{ github.sha }}
          docker push ${{ vars.ECR_URL }}:staging.latest
          docker push ${{ vars.ECR_URL }}:production.latest

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    environment: staging

    env:
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update image tag
        env:
          ECR_URL: ${{ vars.ECR_URL }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cat config/kubernetes/staging/deployment.tpl | envsubst > config/kubernetes/staging/deployment.yaml

      - name: Authenticate to the cluster
        env:
          KUBE_CERT: ${{ secrets.KUBE_CERT }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
          KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
        run: |
          echo "${KUBE_CERT}" > ca.crt
          kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
          kubectl config set-credentials deploy-user --token=${KUBE_TOKEN}
          kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${KUBE_NAMESPACE}
          kubectl config use-context ${KUBE_CLUSTER}

      - name: Rollout restart deployment
        run: |
          kubectl -n ${KUBE_NAMESPACE} apply -f config/kubernetes/staging

      - name: Send deploy notification to product Slack channel
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "#1d990c",
                  "text": "${{ github.actor }} deployed *${{ needs.build.outputs.build-tag }}* to *Staging*",
                  "fields": [
                    {
                      "title": "Project",
                      "value": "Help With Child Arrangements",
                      "short": true
                    }
                  ],
                  "actions": [
                    {
                      "text": "Visit Job",
                      "type": "button",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: ${{ github.ref == 'refs/heads/main' }}
    environment: production

    env:
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update image tag
        env:
          ECR_URL: ${{ vars.ECR_URL }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cat config/kubernetes/production/deployment.tpl | envsubst > config/kubernetes/production/deployment.yaml

      - name: Authenticate to the cluster
        env:
          KUBE_CERT: ${{ secrets.KUBE_CERT }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
          KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
        run: |
          echo "${KUBE_CERT}" > ca.crt
          kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
          kubectl config set-credentials deploy-user --token=${KUBE_TOKEN}
          kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${KUBE_NAMESPACE}
          kubectl config use-context ${KUBE_CLUSTER}

      - name: Rollout restart deployment
        run: |
          kubectl -n ${KUBE_NAMESPACE} apply -f config/kubernetes/production

      - name: Send deploy notification to product Slack channel
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "#1d990c",
                  "text": "${{ github.actor }} deployed *${{ needs.build.outputs.build-tag }}* to *Production*",
                  "fields": [
                    {
                      "title": "Project",
                      "value": "Help With Child Arrangements",
                      "short": true
                    }
                  ],
                  "actions": [
                    {
                      "text": "Visit Job",
                      "type": "button",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Send deploy notification to release Slack channel
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "#1d990c",
                  "text": "${{ github.actor }} deployed *${{ needs.build.outputs.build-tag }}* to *Production*",
                  "fields": [
                    {
                      "title": "Project",
                      "value": "Help With Child Arrangements",
                      "short": true
                    }
                  ],
                  "actions": [
                    {
                      "text": "Visit Job",
                      "type": "button",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.PROD_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
